[project]
name = "microshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
    "pydantic[email]>=2.12.4",
    "ruff>=0.14.6",
    "uvicorn[standard]>=0.38.0",
]
